# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/soc-lab/Desktop/SoC-Lab/SocLabPartialReconfigIot/ImageProcessing/black_white_filter/black_white_filter.srcs/sources_1/bd/zynq_design/ip/zynq_design_rst_ps7_0_100M_0/zynq_design_rst_ps7_0_100M_0.xci
# IP: The module: 'zynq_design_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/soc-lab/Desktop/SoC-Lab/SocLabPartialReconfigIot/ImageProcessing/black_white_filter/black_white_filter.srcs/sources_1/bd/zynq_design/ip/zynq_design_rst_ps7_0_100M_0/zynq_design_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/soc-lab/Desktop/SoC-Lab/SocLabPartialReconfigIot/ImageProcessing/black_white_filter/black_white_filter.srcs/sources_1/bd/zynq_design/ip/zynq_design_rst_ps7_0_100M_0/zynq_design_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/soc-lab/Desktop/SoC-Lab/SocLabPartialReconfigIot/ImageProcessing/black_white_filter/black_white_filter.srcs/sources_1/bd/zynq_design/ip/zynq_design_rst_ps7_0_100M_0/zynq_design_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/soc-lab/Desktop/SoC-Lab/SocLabPartialReconfigIot/ImageProcessing/black_white_filter/black_white_filter.srcs/sources_1/bd/zynq_design/ip/zynq_design_rst_ps7_0_100M_0/zynq_design_rst_ps7_0_100M_0.xci
# IP: The module: 'zynq_design_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/soc-lab/Desktop/SoC-Lab/SocLabPartialReconfigIot/ImageProcessing/black_white_filter/black_white_filter.srcs/sources_1/bd/zynq_design/ip/zynq_design_rst_ps7_0_100M_0/zynq_design_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/soc-lab/Desktop/SoC-Lab/SocLabPartialReconfigIot/ImageProcessing/black_white_filter/black_white_filter.srcs/sources_1/bd/zynq_design/ip/zynq_design_rst_ps7_0_100M_0/zynq_design_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/soc-lab/Desktop/SoC-Lab/SocLabPartialReconfigIot/ImageProcessing/black_white_filter/black_white_filter.srcs/sources_1/bd/zynq_design/ip/zynq_design_rst_ps7_0_100M_0/zynq_design_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
